apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: parser-vars  
spec:
  backendType: systemManager
  region: us-east-2
  data:    
    - key: /auth/client_id
      name: COGNITO_CLIENT_ID    
    - key: /auth/client_secret
      name: COGNITO_CLIENT_SECRET    



